"""Initial

Revision ID: df669ea730c4
Revises: 
Create Date: 2021-08-27 17:01:49.729434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df669ea730c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('long_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_url', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_long_urls_long_url'), 'long_urls', ['long_url'], unique=True)
    op.create_table('short_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short', sa.String(length=16), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('long_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['long_id'], ['long_urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_urls_short'), 'short_urls', ['short'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_urls_short'), table_name='short_urls')
    op.drop_table('short_urls')
    op.drop_index(op.f('ix_long_urls_long_url'), table_name='long_urls')
    op.drop_table('long_urls')
    # ### end Alembic commands ###
