version: '3'

services: 
  app:
    build: 
      context: ./
      dockerfile: ./Dockerfile.app
    entrypoint: [ "sh","/usr/src/app/entrypoint.sh"]
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    expose:
      - 5000
    env_file:
      - .env
    volumes:
      - ./app:/usr/src/app/app
    restart: unless-stopped
    depends_on: 
      - db
  nginx:
    image: nginx:latest
    ports:
      - 80:5000
    volumes: 
      - ./nginx:/etc/nginx/conf.d/ 
    restart: unless-stopped
    depends_on: 
      - app
  db:
    image: postgres:13-alpine
    volumes:
      - pg_data:/var/lib/postgre sql/data/
    env_file:
      - .env
    restart: unless-stopped
volumes:
  pg_data: