version: '3'

services: 
  app:
    build: 
      context: ./
      dockerfile: ./Dockerfile.app
    entrypoint: [ "sh","/usr/src/app/entrypoint.sh"]
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - ./app:/usr/src/app/app
    restart: on-failure
  nginx:
    build: ./nginx
    ports:
      - 80:5000
    restart: on-failure
    depends_on: 
      - app
    